### ISSUE TITLE
Build Tracker-Android: failed

### ISSUE THREAD

**Issue by Mr-SidD** [adsamcik/Tracker-Android#212]
When I cloned the project and ran it in Android Studio, the following message was shown in the build section!

Caused by: org.gradle.api.GradleException: File google-services.json is missing. The Google Services Plugin cannot function without it. 

Please help me solve this issue!

**Comment by adsamcik** [comment]
Hi,
as the message says you need google-services.json for google services such as maps to work. There is an example file that pipelines use that allows building but then the maps might not work https://github.com/adsamcik/Tracker-Android/blob/main/google-services.json.example
